### ISSUE TITLE
panic on RowRepoIter

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#215]
Query:

```sql
SELECT c.message
FROM
    commits c
    JOIN refs r ON r.hash = c.hash
WHERE
    r.name = 'refs/heads/HEAD';
```

Panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xafdf73]

goroutine 39 [running]:
github.com/src-d/gitbase.(*rowRepoIter).rowReader(0xc420216850, 0x1)
	/go/src/github.com/src-d/gitbase/repository_pool.go:293 +0x193
created by github.com/src-d/gitbase.NewRowRepoIter
	/go/src/github.com/src-d/gitbase/repository_pool.go:214 +0x277
opening "/opt/repos" repository...
time="2018-04-12T07:10:36Z" level=info msg="NewConnection: client 1"
time="2018-04-12T07:17:00Z" level=info msg="NewConnection: client 2"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xafdf73]

goroutine 69 [running]:
github.com/src-d/gitbase.(*rowRepoIter).rowReader(0xc4201fa150, 0x1)
	/go/src/github.com/src-d/gitbase/repository_pool.go:293 +0x193
created by github.com/src-d/gitbase.NewRowRepoIter
	/go/src/github.com/src-d/gitbase/repository_pool.go:214 +0x277
```

**Comment by smola** [comment]
Here's the problem: https://github.com/src-d/gitbase/blob/847f97f942875e8979a349032d1c8f8d701080e4/repository_pool.go#L279

**Comment by ajnavarro** [comment]
@smola Are you using `UNSTABLE_SQUASH_ENABLE=1`?

**Comment by smola** [comment]
@ajnavarro No.
