### ISSUE TITLE
Random panics using bblfsh UDF

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#283]
Sometimes gitbase stop working due a grpc error:

```
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201b4418, 0x72, 0xffffffffffffff00, 0x1029660, 0x1a537c0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201b4418, 0xc420b6e000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201b4400, 0xc420b6e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201b4400, 0xc420b6e000, 0x8000, 0x8000, 0x11, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200cc400, 0xc420b6e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc42015ad20, 0xc42021a038, 0x9, 0x9, 0x20, 0xc4202be0e0, 0x7f2367f34b88)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1026a40, 0xc42015ad20, 0xc42021a038, 0x9, 0x9, 0x9, 0xc420d61df0, 0x40451e, 0xc420d61e9f)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0x1026a40, 0xc42015ad20, 0xc42021a038, 0x9, 0x9, 0x44baa8, 0x171fef79e9e1, 0xc420cb4cbc)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/io/io.go:327 +0x58
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.readFrameHeader(0xc42021a038, 0x9, 0x9, 0x1026a40, 0xc42015ad20, 0x0, 0x14400000000, 0x1abf6a0, 0xbeb72e83a0c913e2)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc42021a000, 0xc4202be0e0, 0xc4202be0e0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc4204cd080)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:1195 +0xe1
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:273 +0xbf1

goroutine 13 [select, 24 minutes]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.loopyWriter(0x10352e0, 0xc4200307c0, 0xc4204e8330, 0xc420d5dfb8)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/transport.go:748 +0x368
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc4204cd080)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:305 +0x5e
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:304 +0xd42

goroutine 270 [IO wait]:
internal/poll.runtime_pollWait(0x7f2367f2bbc0, 0x72, 0xc42007abb8)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421696218, 0x72, 0xffffffffffffff00, 0x1029660, 0x1a537c0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc421696218, 0xc42195e000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc421696200, 0xc42195e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc421696200, 0xc42195e000, 0x8000, 0x8000, 0x11, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200cc0b8, 0xc42195e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc4211b4060, 0xc42021a498, 0x9, 0x9, 0x20, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1026a40, 0xc4211b4060, 0xc42021a498, 0x9, 0x9, 0x9, 0xc42007adf0, 0x40451e, 0xc42007ae9f)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0x1026a40, 0xc4211b4060, 0xc42021a498, 0x9, 0x9, 0x44baa8, 0x18745e8bcab7, 0xc429df91a5)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/io/io.go:327 +0x58
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.readFrameHeader(0xc42021a498, 0x9, 0x9, 0x1026a40, 0xc4211b4060, 0x0, 0x29800000000, 0x1abf6a0, 0xbeb72ff129de6910)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc42021a460, 0xc4219238c0, 0xc4219238c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc421d02a80)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:1195 +0xe1
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:273 +0xbf1

goroutine 271 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.loopyWriter(0x10352e0, 0xc420c86100, 0xc421852180, 0xc42007efb8)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/transport.go:748 +0x368
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc421d02a80)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:305 +0x5e
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:304 +0xd42

goroutine 468 [select, 24 minutes]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc4218d8cf0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:108 +0x182
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:94 +0x3f

goroutine 469 [select, 24 minutes]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc42128e440)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x14a
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14c

goroutine 410 [IO wait]:
internal/poll.runtime_pollWait(0x7f2367f2bc90, 0x72, 0xc420d5fbb8)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201b4698, 0x72, 0xffffffffffffff00, 0x1029660, 0x1a537c0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201b4698, 0xc4211ac000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201b4680, 0xc4211ac000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201b4680, 0xc4211ac000, 0x8000, 0x8000, 0x11, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200cc018, 0xc4211ac000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc42015a2a0, 0xc42021a2d8, 0x9, 0x9, 0x20, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1026a40, 0xc42015a2a0, 0xc42021a2d8, 0x9, 0x9, 0x9, 0xc420d5fdf0, 0x40451e, 0xc420d5fe9f)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0x1026a40, 0xc42015a2a0, 0xc42021a2d8, 0x9, 0x9, 0x44baa8, 0x186bc89bcd30, 0xc4314ec5f0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/io/io.go:327 +0x58
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.readFrameHeader(0xc42021a2d8, 0x9, 0x9, 0x1026a40, 0xc42015a2a0, 0x0, 0x29000000000, 0x1abf6a0, 0xbeb72fe7f14d45bf)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc42021a2a0, 0xc420f58780, 0xc420f58780, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc421d02300)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:1195 +0xe1
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:273 +0xbf1

goroutine 470 [select, 24 minutes]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420460000)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:1224 +0x235
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420460000)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:827 +0x1b5
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:818 +0xe1

goroutine 516 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc420c86040)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x14a
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14c

goroutine 517 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc4212b0000)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:1224 +0x235
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc4212b0000)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:827 +0x1b5
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:818 +0xe1

goroutine 411 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.loopyWriter(0x10352e0, 0xc42128e5c0, 0xc420b301b0, 0xc420079fb8)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/transport.go:748 +0x368
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc421d02300)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:305 +0x5e
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:304 +0xd42

goroutine 582 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc420d937a0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:108 +0x182
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:94 +0x3f
```

**Comment by mcarmonaa** [comment]
I couldn't reproduce this panic. It supposes that the panic is raised when the `uast` function is called.

I tried to get it with the `v0.11.0` binary release and directly running the server with `go run`. Also I tried loading different folders with different number of repositories inside them.

I used this query and other variants of it changing limit, the language, etc.:
`'SELECT blobs.hash,uast(blobs.content, "Go") FROM refs INNER JOIN commits ON refs.hash = commits.hash INNER JOIN tree_entries ON commits.tree_hash = tree_entries.tree_hash INNER JOIN blobs ON tree_entries.entry_hash = blobs.hash WHERE language(tree_entries.name, blobs.content) = "Go" limit 50 \G'`

I also used different bblfshd versions: `v2.0.0`, `v2.1.0`, `v2.2.0`, `v2.3.0`,`v2.4.3`

Commands used:
- to run the server:
`go run main.go server -v --git=/path/to/repos -u manu --host=127.0.0.1 -p 3306`
`./gitbase server -v --git=/path/to/repos -u manu --host=127.0.0.1 -p 3306`

- to run the client(mariadb):
`/usr/bin/mysql -q -h 127.0.0.1 -P 3306 -u manu -e 'SELECT blobs.hash,uast(blobs.content, "Go") FROM refs INNER JOIN commits ON refs.hash = commits.hash INNER JOIN tree_entries ON commits.tree_hash = tree_entries.tree_hash INNER JOIN blobs ON tree_entries.entry_hash = blobs.hash WHERE language(tree_entries.name, blobs.content) = "Go" limit 1 \G'`
