### ISSUE TITLE
Panic calling bblfshd

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#329]
Executing the following query:
```
select files.repository_id , array_length(uast(files.blob_content,language(files.file_path,files.blob_content),'//*[@roleFunction and @roleDeclaration]')) from files NATURAL JOIN refs  where language(files.file_path,files.blob_content)= 'Go' and refs.ref_name='HEAD'
```

I got the next error:
```
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x45c845]

goroutine 68 [running, locked to thread]:
runtime.throw(0xe7e583, 0x5)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:589 +0x6a fp=0xc0012f12e8 sp=0xc0012f12b8 pc=0x42ef1a
runtime.sigpanic()
	/home/travis/.gimme/versions/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc0012f1338 sp=0xc0012f12e8 pc=0x443af5
runtime.memmove(0x7f209e939010, 0x6c616e7265746e69, 0x40000000)
	/home/travis/.gimme/versions/go/src/runtime/memmove_amd64.s:389 +0x485 fp=0xc0012f1340 sp=0xc0012f1338 pc=0x45c845
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._Cfunc_CString(0x6c616e7265746e69, 0x656c6f52, 0xc000050f00)
	_cgo_gotypes.go:72 +0x8d fp=0xc0012f1370 sp=0xc0012f1340 pc=0xbbe04d
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.(*cstringPool).getCstring(0x1dbb5c0, 0x6c616e7265746e69, 0x656c6f52, 0xc0012f1400)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/cstring_pool.go:12 +0x39 fp=0xc0012f13c8 sp=0xc0012f1370 pc=0xbbf989
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.goGetInternalType(0xc0010e4550, 0xf9a5a0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:201 +0x43 fp=0xc0012f13f8 sp=0xc0012f13c8 pc=0xbbf4e3
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._cgoexpwrap_dc618b6d429f_goGetInternalType(0xc0010e4550, 0x0)
	_cgo_gotypes.go:243 +0x5a fp=0xc0012f1420 sp=0xc0012f13f8 pc=0xbbe3ea
runtime.call32(0x0, 0x7f211bffe960, 0x7f211bffe9f0, 0x10)
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:522 +0x3b fp=0xc0012f1450 sp=0xc0012f1420 pc=0x4595cb
runtime.cgocallbackg1(0x0)
	/home/travis/.gimme/versions/go/src/runtime/cgocall.go:316 +0x19b fp=0xc0012f14c8 sp=0xc0012f1450 pc=0x4074fb
runtime.cgocallbackg(0x0)
	/home/travis/.gimme/versions/go/src/runtime/cgocall.go:194 +0xd6 fp=0xc0012f1530 sp=0xc0012f14c8 pc=0x4072c6
runtime.cgocallback_gofunc(0x407182, 0xc52ac0, 0xc0012f15c8, 0xf8a1d2)
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:775 +0x9b fp=0xc0012f1550 sp=0xc0012f1530 pc=0x45ab9b
runtime.asmcgocall(0xc52ac0, 0xc0012f15c8)
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:622 +0x42 fp=0xc0012f1558 sp=0xc0012f1550 pc=0x45aa32
runtime.cgocall(0xc52ac0, 0xc0012f15c8, 0xc000f9a1b0)
	/home/travis/.gimme/versions/go/src/runtime/cgocall.go:131 +0x82 fp=0xc0012f1590 sp=0xc0012f1558 pc=0x407182
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._Cfunc_Filter(0xc000c4e000, 0x7f210c008a40, 0x0)
	_cgo_gotypes.go:107 +0x4a fp=0xc0012f15c8 sp=0xc0012f1590 pc=0xbbe18a
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.Filter(0xc000c4e000, 0xc000ba4000, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:119 +0xbd fp=0xc0012f1640 sp=0xc0012f15c8 pc=0xbbf30d
github.com/src-d/gitbase/internal/function.UAST.Eval(0x1116b40, 0xc000048780, 0x1116360, 0xc000c5f5c0, 0x1116de0, 0xc000c5f5e0, 0xc00166ab10, 0xc000a91830, 0x9, 0x9, ...)
	/home/travis/gopath/src/github.com/src-d/gitbase/internal/function/uast.go:201 +0x5d8 fp=0xc0012f1790 sp=0xc0012f1640 pc=0xbc25c8
github.com/src-d/gitbase/internal/function.(*UAST).Eval(0xc00022ca50, 0xc00166aab0, 0xc000a91830, 0x9, 0x9, 0x0, 0x111b360, 0x1dda0e0, 0xc00166aab0)
	<autogenerated>:1 +0x91 fp=0xc0012f1810 sp=0xc0012f1790 pc=0xbc4261
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function.(*ArrayLength).Eval(0xc000c532d0, 0xc00166aab0, 0xc000a91830, 0x9, 0x9, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/arraylength.go:48 +0x129 fp=0xc0012f18a8 sp=0xc0012f1810 pc=0xad0789
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.filterRow(0xc000a9b7d0, 0xc000c5f600, 0x2, 0x2, 0xc000a91830, 0x9, 0x9, 0x70f6d5, 0x1, 0x8, ...)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/project.go:147 +0xd4 fp=0xc0012f1960 sp=0xc0012f18a8 pc=0x7f7e54
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*iter).Next(0xc00000d0e0, 0x0, 0x0, 0x0, 0x2, 0xa)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/project.go:133 +0xc3 fp=0xc0012f19d0 sp=0xc0012f1960 pc=0x7f7cc3
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc000a9bbf0, 0x107, 0xc000c15ee0, 0x1, 0x8, 0xc000b77ad0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:103 +0x47 fp=0xc0012f1a38 sp=0xc0012f19d0 pc=0x75f857
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*limitIter).Next(0xc00000d160, 0xc000c15dfc, 0xc000000107, 0xc000c15ee0, 0x1, 0x8)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/limit.go:79 +0x45 fp=0xc0012f1a78 sp=0xc0012f1a38 pc=0x7f5ce5
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc000a9bc20, 0x2, 0x2, 0xc0014471e0, 0x2, 0x2)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:103 +0x47 fp=0xc0012f1ae0 sp=0xc0012f1a78 pc=0x75f857
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/server.(*Handler).ComQuery(0xc000aff760, 0xc000254100, 0xc0001dc240, 0x115, 0xc000aff840, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/server/handler.go:112 +0x215 fp=0xc0012f1bb8 sp=0xc0012f1ae0 pc=0xae3275
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-vitess.v0/mysql.(*Listener).handle(0xc000031d40, 0x11188e0, 0xc0000c3c58, 0xc000000001, 0xbec2a9cc5201b75d, 0x92770c7b, 0x1dbc480)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-vitess.v0/mysql/server.go:338 +0x9d8 fp=0xc0012f1fa8 sp=0xc0012f1bb8 pc=0xaac9b8
runtime.goexit()
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0012f1fb0 sp=0xc0012f1fa8 pc=0x45b2e1
created by github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-vitess.v0/mysql.(*Listener).Accept
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-vitess.v0/mysql/server.go:163 +0xb9

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f213fb8af00, 0x72, 0x0)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001bd218, 0x72, 0xc00022fc00, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0001bd218, 0xffffffffffffff00, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc0001bd200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:378 +0x1a0
net.(*netFD).accept(0xc0001bd200, 0xc0000c3c58, 0x44cff8, 0x8208b15626a)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:239 +0x42
net.(*TCPListener).accept(0xc0000c3c48, 0xc000243be0, 0xc000243be8, 0x38)
	/home/travis/.gimme/versions/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).Accept(0xc0000c3c48, 0xf9abb0, 0xc000031d40, 0x11188e0, 0xc0000c3c58)
	/home/travis/.gimme/versions/go/src/net/tcpsock.go:260 +0x47
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-vitess.v0/mysql.(*Listener).Accept(0xc000031d40)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-vitess.v0/mysql/server.go:149 +0xd0
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/server.(*Server).Start(0xc0000c3c50, 0x25, 0xc000243d18)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/server/server.go:54 +0x2e
github.com/src-d/gitbase/cmd/gitbase/command.(*Server).Execute(0xc000184180, 0xc0002e6640, 0x0, 0x5, 0xc000184180, 0x1)
	/home/travis/gopath/src/github.com/src-d/gitbase/cmd/gitbase/command/server.go:92 +0x4f4
github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000030420, 0xc0000c8010, 0x5, 0x5, 0xc00031f930, 0x1, 0x2, 0xc000ab6000, 0xc0001bd100)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x800
github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc000030420, 0xe9b0bc, 0x7, 0xf5fbd7, 0x1c, 0xf5fbd7)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/home/travis/gopath/src/github.com/src-d/gitbase/cmd/gitbase/main.go:29 +0x29a

goroutine 39 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc000c2dbf0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:108 +0x142
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:94 +0x3f

goroutine 40 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000ca1c80)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x10f
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x13a

goroutine 41 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc0000f0b40)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:1224 +0x1c1
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc0000f0b40)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:827 +0x1b2
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:818 +0xe1

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f213fb8ad60, 0x72, 0xc00007abc0)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001bdd18, 0x72, 0xffffffffffffff00, 0x1105120, 0x1d500a8)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0001bdd18, 0xc00103e000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0001bdd00, 0xc00103e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:163 +0x179
net.(*netFD).Read(0xc0001bdd00, 0xc00103e000, 0x8000, 0x8000, 0x0, 0x0, 0x50)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:203 +0x4f
net.(*conn).Read(0xc0000c2018, 0xc00103e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/net.go:176 +0x68
bufio.(*Reader).Read(0xc00103c000, 0xc0001c61f8, 0x9, 0x9, 0x20, 0xc000de2000, 0x7f213faa9d28)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x1102680, 0xc00103c000, 0xc0001c61f8, 0x9, 0x9, 0x9, 0xc001146060, 0x405c6e, 0xc00007aea3)
	/home/travis/.gimme/versions/go/src/io/io.go:310 +0x88
io.ReadFull(0x1102680, 0xc00103c000, 0xc0001c61f8, 0x9, 0x9, 0x44cff8, 0x820e7911808, 0xc032e2a3bb)
	/home/travis/.gimme/versions/go/src/io/io.go:329 +0x58
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.readFrameHeader(0xc0001c61f8, 0x9, 0x9, 0x1102680, 0xc00103c000, 0x0, 0x0, 0x1dbc480, 0xbec2a9ccb2dee471)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001c61c0, 0xc000de2000, 0xc000de2000, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc000478180)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:1195 +0xe2
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:273 +0xb62

goroutine 22 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.loopyWriter(0x1111740, 0xc000ca1d40, 0xc000c3c1b0, 0xc00105bfb8)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/transport.go:748 +0x336
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc000478180)
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:305 +0x5e
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:304 +0xcb1

```

**Comment by erizocosmico** [comment]
Opened an issue in bblfsh, since this is reproducible outside gitbase https://github.com/bblfsh/client-go/issues/60

Keeping this open to remember to update the bblfsh dependency once this is fixed.
