### ISSUE TITLE
Panic for full scan queries with index

### ISSUE THREAD

**Issue by kuba--** [src-d/gitbase#472]
gitbase master:
```
*   commit 0082a18f112514d5bc0704a960493742cb2a8320 (HEAD -> master, origin/master, origin/HEAD)
|\  Merge: 466a785 b3301e0
| | Author: Antonio Navarro Perez <antnavper@gmail.com>
| | Date:   Mon Sep 10 17:21:02 2018 +0200
| | 
| |     Merge pull request #465 from jfontan/improvement/embed-git-repository
| |     
| |     gitbase: embded git.Repository in gitbase.Repository
| | 
| * commit b3301e0418a6a552ce4108118d22ffcf4886eef2
|/  Author: Javi Fontan <jfontan@gmail.com>
|   Date:   Fri Sep 7 14:10:32 2018 +0200
|   
|       gitbase: embded git.Repository in gitbase.Repository
|       
|       Signed-off-by: Javi Fontan <jfontan@gmail.com>
|   
*   commit 466a7854d50c6d834608ca8ffb303e4ca93fb4a0 (tag: v0.17.0-RC1)
```

I run following queries:
```sql
CREATE INDEX email_idx ON commits USING pilosalib (commit_author_email);
SELECT count(*) FROM commits WHERE commit_author_email!='kuba@sourced.tech';
```

This panics with following stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4a019c9]

goroutine 60 [running]:
github.com/src-d/gitbase/vendor/github.com/pilosa/pilosa.(*Field).Name(...)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/github.com/pilosa/pilosa/field.go:188
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosalib.(*negateLookup).values(0xc000cab7a0, 0x4f67de0, 0xc001072000, 0x0, 0x0, 0x0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosalib/lookup.go:360 +0x349
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosalib.(*negateLookup).Values(0xc000cab7a0, 0x4f67de0, 0xc001072000, 0x0, 0x0, 0x0, 0x0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosalib/lookup.go:425 +0xa5
github.com/src-d/gitbase.(*commitsTable).PartitionRows.func1(0xc000a80300, 0xb, 0xb, 0x4cd227d, 0x7)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/commits.go:94 +0xfc
github.com/src-d/gitbase.rowIterWithSelectors(0xc000a802a0, 0x5ba4e40, 0xb, 0xb, 0x4cd227d, 0x7, 0xc00015fd50, 0x1, 0x1, 0xc000ccfda8, ...)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/filters.go:339 +0x115
github.com/src-d/gitbase.(*commitsTable).PartitionRows(0xc000a81590, 0xc000a802a0, 0x4f67de0, 0xc001072000, 0xc0020d2020, 0xc001072000, 0xc00005a658, 0x44a64b1)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/commits.go:83 +0x1f5
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangePartition).RowIter(0xc0020d2040, 0xc000a81920, 0x4f7fb80, 0xc0020d2040, 0x0, 0x0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:298 +0x4f
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).iterPartition(0xc00026f920, 0x4f67de0, 0xc001072000)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:220 +0xcc
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start.func1(0xc00026f920, 0xc001053630, 0x4f67de0, 0xc001072000)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:168 +0x3f
created by github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:167 +0x10d
```

**Comment by kuba--** [comment]
I tested agains pga repos:
`pga list -l python -f json | head -n 10 | jq -r '.sivaFilenames[]' | pga get -i -o repos`

**Comment by erizocosmico** [comment]
There are several issues here:

- We never check field is nil when we get it from the index, and it actually can be nil if it's not found. It should throw an error instead of panicking.
- After saving, all the fields in the index are present, but when querying, some are missing. I just don't know why yet, I'll keep investigating. Nobody is deleting the fields or overwriting them, so not really sure what's going on.

**Comment by kuba--** [comment]
If we use just a one partition, will that work?

**Comment by erizocosmico** [comment]
Ok, this does not happen with `--parallelism=1`, so it means something we're using is not thread-safe.

**Comment by erizocosmico** [comment]
Now that #363 is merged it should be working fine. Can you confirm, @kuba--?

**Comment by kuba--** [comment]
@erizocosmico I've double checked **master** gitbase with the latest mysql **e8316f5430855f55b0da4b5c63fc990d75c2c085** and looks that it works for _pilosalib_, but not for old _pilosa_ driver.

Here is a panic stacktrace which I got:
```
DEBU[0021] executing query                               query="CREATE INDEX email_idx ON commits USING pilosa (commit_author_email)"
INFO[0021] starting to save the index                    async=true driver=pilosa id=email_idx
DEBU[0021] executing query                               query="SHOW DATABASES"
DEBU[0023] finished pilosa indexing                      duration=1.673326163s id=email_idx mapping=33.368086ms pilosa=92.958517ms rows=9865
INFO[0023] index successfully created                    driver=pilosa id=email_idx
DEBU[0024] executing query                               query="SHOW INDEXES FROM commits"
DEBU[0025] executing query                               query="SHOW INDEXES FROM commits"
DEBU[0033] executing query                               query="SELECT count(*) FROM commits WHERE commit_author_email!='kuba@sourced.tech'"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x495cdea]

goroutine 129 [running]:
github.com/src-d/gitbase/vendor/github.com/boltdb/bolt.(*DB).page(...)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/github.com/boltdb/bolt/db.go:796
github.com/src-d/gitbase/vendor/github.com/boltdb/bolt.(*Tx).page(...)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/github.com/boltdb/bolt/tx.go:578
github.com/src-d/gitbase/vendor/github.com/boltdb/bolt.(*Bucket).pageNode(0xc001231840, 0x306, 0x203000, 0x203000)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/github.com/boltdb/bolt/bucket.go:726 +0xaa
github.com/src-d/gitbase/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc000a3da88, 0xc000a3daf0, 0x8, 0x8, 0x306)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/github.com/boltdb/bolt/cursor.go:254 +0x50
github.com/src-d/gitbase/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc000a3da88, 0xc000a3daf0, 0x8, 0x8, 0x0, 0x0, 0xc00004ea00, 0xc000a3dab8, 0x403e51a, 0xc001ada960, ...)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/github.com/boltdb/bolt/cursor.go:159 +0xa5
github.com/src-d/gitbase/vendor/github.com/boltdb/bolt.(*Bucket).Get(0xc001231840, 0xc000a3daf0, 0x8, 0x8, 0x402b532, 0xc000000008, 0xc00102a140)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/github.com/boltdb/bolt/bucket.go:267 +0xcd
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa.(*mapping).getLocationFromBucket.func1(0xc000000008, 0x4df08d0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/mapping.go:320 +0x65
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa.(*mapping).query(0xc00105e9b0, 0xc000a3dba8, 0x0, 0x0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/mapping.go:88 +0x9a
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa.(*mapping).getLocationFromBucket(0xc00105e9b0, 0xc001231840, 0x82, 0x5bef340, 0x4aee6e0, 0xc001876150, 0xc000a3dc38, 0x402b532)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/mapping.go:316 +0x7e
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa.(*indexValueIter).Next(0xc0016cfdb0, 0x4dee0c8, 0xc0018761a0, 0x4f7b8c0, 0xc0016cfdb0, 0x5bef340)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/iterator.go:74 +0x7c
github.com/src-d/gitbase.(*commitsIndexIter).Next(0xc0016cfe00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/commits.go:409 +0xc2
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*FilterIter).Next(0xc00122d920, 0xc00009e000, 0xc000a3ddf8, 0x40d73cd, 0xc000cc6810, 0x0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/filter.go:105 +0x38
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc00122d950, 0x40d8a1c, 0xc001fdf2f0, 0xc002a4e900, 0xc000a3de58, 0x40d8a1c)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:178 +0x47
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*trackedRowIter).Next(0xc001bc2040, 0xc000a3deac, 0x3, 0x2, 0x0, 0x0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/process.go:101 +0x37
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).iterPartition(0xc00230cea0, 0x4f77760, 0xc001b71db0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:241 +0x251
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start.func1(0xc00230cea0, 0xc002042d30, 0x4f77760, 0xc001b71db0)
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:168 +0x3f
created by github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start
	/Users/kuba/Workspace/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:167 +0x10d
```

**Comment by kuba--** [comment]
Of course with `--parallelism=1` it work on both drivers.

**Comment by erizocosmico** [comment]
Right, I only fixed it for pilosalib. Pilosa might need almost the exact same fixes.

**Comment by erizocosmico** [comment]
Since we're removing pilosa and renaming pilosalib to pilosa, should we close this issue and add the "migrate pilosalib to pilosa" one to take care of this?

**Comment by ajnavarro** [comment]
sounds good.
