### ISSUE TITLE
Panic creating index

### ISSUE THREAD

**Issue by jfontan** [src-d/gitbase#484]
Using repositories under my `$GOPATH/src/github.com`.

Index creation:

```sql
CREATE INDEX files_commit_path_blob_idx ON commit_files USING pilosa (commit_hash, file_path, blob_hash);
```

Stack trace:

```
DEBU[0008] still creating index                          driver=pilosa duration=1.232560436s id=files_commit_path_blob_idx rows=10000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbbab0c]

goroutine 20 [running]:
github.com/src-d/gitbase.(*commitFilesKeyValueIter).Next(0xc0012f60f0, 0x8, 0xc000c8d760, 0xd60aed, 0xc0001fe000, 0xc000a34918, 0x8, 0x8, 0xc000a34918)
	/home/jfontan/go/src/github.com/src-d/gitbase/commit_files.go:453 +0xfc
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*evalKeyValueIter).Next(0xc0012f6140, 0xc000a34910, 0x8, 0x8, 0xc001304480, 0xa6, 0x11c, 0x0, 0x0)
	/home/jfontan/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go:372 +0x49
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*loggingKeyValueIter).Next(0xc0012f6190, 0xc000f0a660, 0x0, 0xf2de, 0xc001304480, 0xa6, 0x11c, 0x0, 0x0)
	/home/jfontan/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go:475 +0xa4
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa.(*Driver).savePartition(0xc000a31700, 0xc000da68a0, 0x137d0a0, 0xc000dda240, 0x1381740, 0xc0012f6190, 0xc000b6c070, 0xc0001cfc70, 0xad0a, 0xc000c8dc48, ...)
	/home/jfontan/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/driver.go:272 +0x5d2
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa.(*Driver).Save(0xc000a31700, 0xc000da68a0, 0x13944c0, 0xc0001cfc70, 0x1381780, 0xc000d872e0, 0x0, 0x0)
	/home/jfontan/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/driver.go:348 +0x446
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*CreateIndex).createIndex(0xc0001cfc00, 0xc000dd6180, 0xc000de0320, 0x138f080, 0xc000a31700, 0x13944c0, 0xc0001cfc70, 0x13815c0, 0xc000dc4360, 0xc000dea3c0, ...)
	/home/jfontan/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go:187 +0x45c
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*CreateIndex).RowIter.func1()
	/home/jfontan/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go:155 +0x84
created by github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*CreateIndex).RowIter
	/home/jfontan/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go:161 +0x837
exit status 2
```

**Comment by jfontan** [comment]
This pilosa driver will be removed.
