### ISSUE TITLE
close on closed channel

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#524]
Currently running on a new issue, I assume due to the latest version of pilosa?

These are the logs

```bash
~/go/bin/gitbase server -v -d siva --host 0.0.0.0
DEBU[0000] registered database to catalog                db=
DEBU[0000] registered all available functions in catalog 
DEBU[0000] created index storage                        
DEBU[0000] registered pilosa index driver               
INFO[0000] squash tables rule is enabled                
panic: close of closed channel
goroutine 1 [running]:
github.com/src-d/gitbase/vendor/github.com/pilosa/pilosa.(*Holder).Open(0xc0002e19a0, 0x0, 0x0)
        /home/francesc/go/src/github.com/src-d/gitbase/vendor/github.com/pilosa/pilosa/holder.go:153 +0x2f1
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa.(*Driver).LoadAll(0xc0003ad580, 0x0, 0x0, 0x1139e66, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/francesc/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/driver.go:155 +0x264
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*IndexRegistry).LoadIndexes(0xc0002e1720, 0xc0002c8d50, 0x1, 0x1, 0x0, 0x0)
        /home/francesc/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index.go:215 +0x39d
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server%2ev0.(*Engine).Init(0xc0002c8d40, 0x1, 0x1)
        /home/francesc/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/engine.go:99 +0x4c
github.com/src-d/gitbase/cmd/gitbase/command.(*Server).buildDatabase(0xc0001d0fd0, 0x0, 0x0)
        /home/francesc/go/src/github.com/src-d/gitbase/cmd/gitbase/command/server.go:201 +0x2b4
github.com/src-d/gitbase/cmd/gitbase/command.(*Server).Execute(0xc0001d0fd0, 0xc00015d320, 0x0, 0x6, 0x0, 0x0)
        /home/francesc/go/src/github.com/src-d/gitbase/cmd/gitbase/command/server.go:108 +0x60
github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc00015d2c0, 0xc000194010, 0x6, 0x6, 0xc0002c8c20, 0x1, 0x2, 0xc000280510, 0xc000234500)
        /home/francesc/go/src/github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x800
github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc00015d2c0, 0x1100a43, 0x7, 0x11c7713, 0x1c, 0x11c7713)
        /home/francesc/go/src/github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
        /home/francesc/go/src/github.com/src-d/gitbase/cmd/gitbase/main.go:51 +0x39d
```

**Comment by campoy** [comment]
After deleting the `/var/lib/gitbase/index` directory it started working again, so now I'm wondering whether the problem was a specific index that was corrupted.

**Comment by campoy** [comment]
After investigating a bit more it could be the case that this request caused a panic:

```sql
SELECT *
FROM (SELECT language, COUNT(repository_id) AS repository_count
      FROM   (SELECT DISTINCT
                r.repository_id,
                LANGUAGE(t.tree_entry_name, b.blob_content) AS language
              FROM   refs r
                      JOIN commits c ON r.commit_hash = c.commit_hash
                      JOIN commit_trees ct ON c.commit_hash = ct.commit_hash
                      JOIN tree_entries t ON ct.tree_hash = t.tree_hash
                      JOIN blobs b ON t.blob_hash = b.blob_hash
              WHERE  r.ref_name = 'HEAD') AS q1
      GROUP  BY language) AS q2
ORDER  BY repository_count DESC 
```

and that might have caused the corruption on the index.
