### ISSUE TITLE
Crash on start with siva files

### ISSUE THREAD

**Issue by kuba--** [src-d/gitbase#671]
```
 pga list -l python -f json | head -n 1 | jq -r '.sivaFilenames[]' | pga get -i -o repos

./gitbase server -v -d /tmp/repos/ -i /tmp/index

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x184cab4]

goroutine 1 [running]:
github.com/src-d/gitbase.readRefs(0x2035380, 0xc000a27410, 0x14, 0x20, 0x14, 0x0, 0x0)
	/github.com/src-d/gitbase/checksum.go:98 +0x204
github.com/src-d/gitbase.(*checksumable).Checksum(0xc000a27500, 0x0, 0x0, 0x0, 0x0)
	/github.com/src-d/gitbase/checksum.go:32 +0x1ce
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*IndexRegistry).LoadIndexes(0xc000a19ae0, 0xc0004a7aa0, 0x2, 0x2, 0x0, 0x0)
	/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index.go:233 +0x7c7
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server%2ev0.(*Engine).Init(0xc0004a7520, 0x1, 0x1)
	/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/engine.go:121 +0x43
github.com/src-d/gitbase/cmd/gitbase/command.(*Server).buildDatabase(0xc0001382a0, 0xc0004a74a0, 0xc00000f3c0)
	/github.com/src-d/gitbase/cmd/gitbase/command/server.go:225 +0x319
github.com/src-d/gitbase/cmd/gitbase/command.(*Server).Execute(0xc0001382a0, 0xc00026c420, 0x0, 0x6, 0x0, 0x0)
	/github.com/src-d/gitbase/cmd/gitbase/command/server.go:131 +0x23d
github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc00026c3c0, 0xc00003a080, 0x6, 0x6, 0xc000a248b0, 0x1, 0x2, 0xc00012c630, 0xc000480e00)
	/github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x80b
github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc00026c3c0, 0x1d7f997, 0x7, 0x1e4787d, 0x1c, 0x1e4787d)
	/github.com/src-d/gitbase/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/github.com/src-d/gitbase/cmd/gitbase/main.go:52 +0x39d
```

**Comment by kuba--** [comment]
It happens in `checksum` file. The question is why do we have:
```go
	head, err := repo.Head()
	if err != nil && err != plumbing.ErrReferenceNotFound {
		return nil, err
	} else {
		buf.WriteString("HEAD")
		buf.WriteString(head.Hash().String())
	}
```
What to do if we get `plumbing.ErrReferenceNotFound`? Then `head` is nil so we cannot call `Hash`.
@erizocosmico should know more details.

**Comment by kuba--** [comment]
Moreover if there is a `HEAD` ref. we'll write it twice, because of below `refs.ForEach`.
Last but not least - `refs.ForEach` is like iterating through the map. You'll not get always the same order, so maybe we should sort it first.

**Comment by erizocosmico** [comment]
@kuba-- are you sure HEAD is returned in `.References()`? I checked when I was implementing it and it did not.

**Comment by kuba--** [comment]
@erizocosmico - Yes, I tested `go-git` against: `https://github.com/git-fixtures/basic.git`
here: https://github.com/src-d/go-git/blob/master/plumbing/object/commit_walker.go#L215

And this is what I got:
```
addReference: refs/heads/master 36656366306566326332646666623739363033336535613032323139616638366563363538346535
addReference: refs/tags/v1.0.0 36656366306566326332646666623739363033336535613032323139616638366563363538346535
addReference: refs/heads/master 36656366306566326332646666623739363033336535613032323139616638366563363538346535
addReference: HEAD 30303030303030303030303030303030303030303030303030303030303030303030303030303030
addReference: refs/remotes/origin/master 36656366306566326332646666623739363033336535613032323139616638366563363538346535
addReference: refs/remotes/origin/branch 65386433666661623535323839356331396239666366376161323634643237376364653333383831
```
