### ISSUE TITLE
sqlalchemy can't recognize type int64

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase#808]
Affected tables: `blobs`, `files`, `ref_commits`.
Gitbase: v0.20.0-rc1

```
2019-05-01 17:47:56,146:INFO:root:Database.get_sqla_engine(). Masked URL: mysql://root:XXXXXXXXXX@gitbase:3306/gitbase
/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'int64' of column 'blob_size'
  "Did not recognize type '%s' of column '%s'" % (type_, name)
2019-05-01 17:47:56,339:ERROR:root:Unrecognized data type in blobs.blob_size
2019-05-01 17:47:56,340:ERROR:root:Can't generate DDL for NullType(); did you forget to specify a type on this Column?
Traceback (most recent call last):
  File "/home/superset/superset/connectors/sqla/models.py", line 870, in fetch_metadata
    datatype = col.type.compile(dialect=db_dialect).upper()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 580, in compile
    return dialect.type_compiler.process(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 400, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3350, in visit_null
    "type on this Column?" % type_
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?
```

**Comment by smacker** [comment]
A bit more info:

sqlalchemy runs
```
SHOW CREATE TABLE `files`
```

It returns:
```
files	CREATE TABLE `files` (
  `repository_id` text NOT NULL,
  `file_path` text NOT NULL,
  `blob_hash` text NOT NULL,
  `tree_hash` text NOT NULL,
  `tree_entry_mode` text NOT NULL,
  `blob_content` blob NOT NULL,
  `blob_size` int64 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

But according to [documentation](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html) `int64` is incorrect type.

**Comment by erizocosmico** [comment]
@ajnavarro it's actually a bug, not a third party issue. The issue here is that we're not returning the correct type name on the create table.

**Comment by erizocosmico** [comment]
Will be solved when https://github.com/src-d/go-mysql-server/issues/702 is added to gitbase
