### ISSUE TITLE
SELECT * FROM remotes; fails

### ISSUE THREAD

**Issue by zurk** [src-d/gitbase#819]
I found a bug which looks like:
```
mysql> SELECT * FROM remotes;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query
```
And in the logs of gitbase I can see:
```
time="2019-05-20T11:55:05Z" level=info msg="NewConnection: client 1"
time="2019-05-20T11:55:05Z" level=error msg="Error parsing auth server config: unexpected end of JSON input"
time="2019-05-20T11:55:05Z" level=info msg="audit trail" action=authentication address="172.17.0.1:57806" success=true system=audit user=root
time="2019-05-20T11:55:05Z" level=debug msg="executing query" query="SELECT * FROM remotes"
time="2019-05-20T11:55:05Z" level=info msg="audit trail" action=authorization address="172.17.0.1:57806" connection_id=1 permission=read pid=1 query="SELECT * FROM remotes" success=true system=audit user=root
panic: runtime error: index out of range

goroutine 5 [running]:
github.com/src-d/gitbase.remoteToRow(...)
	/go/src/github.com/src-d/gitbase/remotes.go:185
github.com/src-d/gitbase.(*remotesRowIter).Next(0xc00119e3c0, 0xde75b8f49, 0x21fa780, 0xc00117a0c0, 0xc001178b10, 0xc001193ef8)
	/go/src/github.com/src-d/gitbase/remotes.go:165 +0x4e9
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc00119c280, 0xc001193e58, 0x4dc31d, 0xc0010d8b90, 0xc001193ef8, 0x1)
	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:346 +0x5d
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*trackedRowIter).Next(0xc00118a660, 0xc001193eac, 0x3, 0x2, 0x0, 0x0)
	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/process.go:145 +0x37
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).iterPartition(0xc0010d4b40, 0x14cfc40, 0xc001188000)
	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:245 +0x251
github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start.func1(0xc0010d4b40, 0xc001184000, 0x14cfc40, 0xc001188000)
	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:170 +0x3f
created by github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start
	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:169 +0x10d
```

**How to reproduce**
```bash
docker run --rm --name gitbase -p 3306:3306 -v /tmp/repos/:/opt/repos srcd/gitbase:latest
```
There is only one repo inside `/tmp/repos` and with another repository, I cannot reproduce this bug, so I upload it to https://drive.google.com/open?id=1VIAtggnreTo5GCi2ap6EQe3_rjRtCfXt (Sorry for an external link, but GitHub does not allow me to attach 30mb file ). 

and after
```bash
➜  ~ mysql -u root -h 127.0.0.1
mysql> SELECT * FROM remotes;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

**Comment by ajnavarro** [comment]
This is already fixed in latest rc. To use it execute the following docker command:
`docker run --rm --name gitbase -p 3306:3306 -v /tmp/repos/:/opt/repos srcd/gitbase:v0.20.0-rc2`

**Comment by zurk** [comment]
Thanks, @ajnavarro, it works!
