### ISSUE TITLE
Unrecovered panic on remote squash iterator

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#820]
Query:
```sql
SELECT
    SUBSTRING(repository_id_part, 1, ARRAY_LENGTH(SPLIT(repository_id_part, ''))-4) AS repository_id,
    commit_author_when,
    commit_type
FROM (
SELECT
    SUBSTRING(remote_fetch_url, 18) AS repository_id_part,
    commit_author_when,
    CASE ARRAY_LENGTH(commit_parents) WHEN 0 THEN 'Commit' WHEN 1 THEN 'Commit' ELSE 'Merge' END AS commit_type
FROM remotes
NATURAL JOIN refs
NATURAL JOIN commits
) AS q
LIMIT 1000;
```

Trace:
```
gitbase_1     | time="2019-05-20T19:06:46Z" level=info msg="audit trail" action=authorization address="172.18.0.8:59692" connection_id=3 permission=read pid=32 query="SELECT\n    SUBSTRING(repository_id_part, 1, ARRAY_LENGTH(SPLIT(repository_id_part, ''))-4) AS repository_id,\n    commit_author_when,\n    commit_type\nFROM (\nSELECT\n    SUBSTRING(remote_fetch_url, 18) AS repository_id_part,\n    commit_author_when,\n    CASE ARRAY_LENGTH(commit_parents) WHEN 0 THEN 'Commit' WHEN 1 THEN 'Commit' ELSE 'Merge' END AS commit_type\nFROM remotes\nNATURAL JOIN refs\nNATURAL JOIN commits\n) AS q LIMIT 1000" success=true system=audit user=root
gitbase_1     | panic: runtime error: index out of range
gitbase_1     | 
gitbase_1     | goroutine 107 [running]:
gitbase_1     | github.com/src-d/gitbase.(*squashRemoteIter).Advance(0xc000287730, 0xc000488780, 0xffffffff00000006)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/squash_iterator.go:213 +0x6b6
gitbase_1     | github.com/src-d/gitbase.(*squashRemoteRefsIter).Advance(0xc000287810, 0x492bf5, 0xc0013e0360)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/squash_iterator.go:828 +0x5b6
gitbase_1     | github.com/src-d/gitbase.(*squashRefHeadCommitsIter).Advance(0xc000d2afa0, 0x5ce2fac6, 0xc0143769e6)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/squash_iterator.go:1661 +0x6a
gitbase_1     | github.com/src-d/gitbase.(*chainableRowIter).Next(0xc0015873a0, 0x6a9857cd8, 0x23057a0, 0x7efd78808788, 0x0, 0xc0000b1b40)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/squash.go:150 +0x37
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc000d2aff0, 0x10ef320, 0xc000d2c8e0, 0x157c4e0, 0xc0015872a0, 0xc0015a9c10)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:346 +0x5d
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*trackedRowIter).Next(0xc000d2c8e0, 0xc0015a9bf0, 0x44aa68, 0x67f5b5ce3635, 0xc0143768ea, 0x143768ea00d2b040)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/process.go:145 +0x37
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*FilterIter).Next(0xc000c8d170, 0x6a9857bde, 0x23057a0, 0x40cc7f, 0xc000d2b090, 0x50)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/filter.go:105 +0x38
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc000d2b040, 0x0, 0x44aa68, 0x67f5b5ce35d7, 0x1437688c, 0x1437688c01580bc0)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:346 +0x5d
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*iter).Next(0xc000d2c900, 0x6a9857b80, 0x23057a0, 0x3, 0x3, 0xc0015a9eb2)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/project.go:129 +0x38
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc000d2b090, 0x50, 0x44aa68, 0x67f5b5ce354a, 0xc01437679b, 0x1437679b015a9e58)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:346 +0x5d
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*iter).Next(0xc000d2c920, 0x6a9857af3, 0x23057a0, 0x4dd0ec, 0xc0014e9ec0, 0xc001603020)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/project.go:129 +0x38
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql.(*spanIter).Next(0xc000d2b0e0, 0xc0015a9eac, 0x3, 0x2, 0xc0013e0200, 0x0)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go:346 +0x5d
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).iterPartition(0xc0013e0240, 0x157c4e0, 0xc0015872a0)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:245 +0x251
gitbase_1     | github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start.func1(0xc0013e0240, 0xc0004886b0, 0x157c4e0, 0xc0015872a0)
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:170 +0x3f
gitbase_1     | created by github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan.(*exchangeRowIter).start
gitbase_1     | 	/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go:169 +0x10d
```

**Comment by erizocosmico** [comment]
Cannot reproduce. Can you give me the list of repositories you're using or try to reduce it to the repository that fails?

**Comment by erizocosmico** [comment]
Adding blocked label until we got a reproducible case

**Comment by smola** [comment]
`git clone --bare git://github.com/cloudfoundry/cli.git`

Tested now on gitbase-0.20.0-rc3, getting the same panic.
